"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  // IdProduct: DataTypes.STRING,
  // NameProduct: DataTypes.STRING,
  // BreakTime: DataTypes.INTEGER,
  // WashingTime: DataTypes.INTEGER,
  // Type: DataTypes.STRING,
  // MixingTime: DataTypes.INTEGER,
  // Volume: DataTypes.INTEGER,
  // Color: DataTypes.INTEGER,
  // StandardWeight: DataTypes.INTEGER,
  // Error: DataTypes.FLOAT,
  // DateTime: DataTypes.DATE,
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert("Products", [
      {
        IdProduct: "SM1",
        NameProduct: "Lon lon",
        BreakTime: 5,
        WashingTime: 4,
        Type: "L",
        MixingTime: 7,
        Volume: 40,
        Color: "#66FF99",
        StandardWeight: 12,
        Error: 12,
        DateTime: null,
      },
      {
        IdProduct: "SM2",
        NameProduct: "Lon lon",
        BreakTime: 5,
        WashingTime: 4,
        Type: "M",
        MixingTime: 7,
        Volume: 40,
        Color: "#FFCCFF",
        StandardWeight: 12,
        Error: 12,
        DateTime: null,
      },
      {
        IdProduct: "SM3",
        NameProduct: "Lon lon",
        BreakTime: 5,
        WashingTime: 4,
        Type: "S",
        MixingTime: 7,
        Volume: 40,
        Color: "#CCCCFF",
        StandardWeight: 12,
        Error: 12,
        DateTime: null,
      },
      {
        IdProduct: "MD1",
        NameProduct: "Lon trung binh",
        BreakTime: 7,
        WashingTime: 5,
        Type: "M",
        MixingTime: 4,
        Volume: 42,
        Color: "#0000FF",
        StandardWeight: 3,
        Error: 11,
        DateTime: null,
      },
      {
        IdProduct: "MD2",
        NameProduct: "Lon nho",
        BreakTime: 3,
        WashingTime: 8,
        Type: "S",
        MixingTime: 4,
        Volume: 47,
        Color: "#00BB00",
        StandardWeight: 12,
        Error: 3,
        DateTime: null,
      },
      {
        IdProduct: "MD3",
        NameProduct: "Lon trung binh",
        BreakTime: 5,
        WashingTime: 4,
        Type: "L",
        MixingTime: 7,
        Volume: 40,
        Color: "#CC99FF",
        StandardWeight: 12,
        Error: 12,
        DateTime: null,
      },
      {
        IdProduct: "MD4",
        NameProduct: "Lon nho",
        BreakTime: 3,
        WashingTime: 8,
        Type: "S",
        MixingTime: 4,
        Volume: 47,
        Color: "#FF3366",
        StandardWeight: 12,
        Error: 3,
        DateTime: null,
      },
      {
        IdProduct: "LR1",
        NameProduct: "Lon trung binh",
        BreakTime: 5,
        WashingTime: 4,
        Type: "L",
        MixingTime: 7,
        Volume: 40,
        Color: "#993300",
        StandardWeight: 12,
        Error: 12,
        DateTime: null,
      },
      {
        IdProduct: "LR1",
        NameProduct: "Lon trung binh",
        BreakTime: 5,
        WashingTime: 4,
        Type: "L",
        MixingTime: 7,
        Volume: 40,
        Color: "#FF00FF",
        StandardWeight: 12,
        Error: 12,
        DateTime: null,
      },
      {
        IdProduct: "LR2",
        NameProduct: "Lon lớn",
        BreakTime: 5,
        WashingTime: 4,
        Type: "L",
        MixingTime: 7,
        Volume: 40,
        Color: "#FF6600",
        StandardWeight: 12,
        Error: 12,
        DateTime: null,
      },
      {
        IdProduct: "LR3",
        NameProduct: "Lon nhỏ",
        BreakTime: 5,
        WashingTime: 4,
        Type: "L",
        MixingTime: 7,
        Volume: 40,
        Color: "#FF6699",
        StandardWeight: 12,
        Error: 12,
        DateTime: null,
      },
      {
        IdProduct: "LR4",
        NameProduct: "Lon trung binh",
        BreakTime: 5,
        WashingTime: 4,
        Type: "L",
        MixingTime: 7,
        Volume: 40,
        Color: "#FF3399",
        StandardWeight: 12,
        Error: 12,
        DateTime: null,
      },
      {
        IdProduct: "LR5",
        NameProduct: "Lon trung binh",
        BreakTime: 5,
        WashingTime: 4,
        Type: "L",
        MixingTime: 7,
        Volume: 40,
        Color: "#99CC66",
        StandardWeight: 12,
        Error: 12,
        DateTime: null,
      },
      {
        IdProduct: "LR6",
        NameProduct: "Lon trung binh",
        BreakTime: 5,
        WashingTime: 4,
        Type: "L",
        MixingTime: 7,
        Volume: 40,
        Color: "#CCCCFF",
        StandardWeight: 12,
        Error: 12,
        DateTime: null,
      },
      {
        IdProduct: "LR7",
        NameProduct: "Lon trung binh",
        BreakTime: 5,
        WashingTime: 4,
        Type: "L",
        MixingTime: 7,
        Volume: 40,
        Color: "#CCFFFF",
        StandardWeight: 12,
        Error: 12,
        DateTime: null,
      },
      {
        IdProduct: "LR8",
        NameProduct: "Lon trung binh",
        BreakTime: 5,
        WashingTime: 4,
        Type: "L",
        MixingTime: 7,
        Volume: 40,
        Color: "#99FF66",
        StandardWeight: 12,
        Error: 12,
        DateTime: null,
      },
      {
        IdProduct: "LR9",
        NameProduct: "Lon trung binh",
        BreakTime: 5,
        WashingTime: 4,
        Type: "L",
        MixingTime: 7,
        Volume: 40,
        Color: "#33FF33",
        StandardWeight: 12,
        Error: 12,
        DateTime: null,
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
